# This is a basic workflow to help you get started with Actions

name: validate-pr-acceptance

# Controls when the action will run. 
on:
  pull_request_target:
    types: [ opened, edited, reopened, synchronized ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  branch-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: branch_chack_acceptance
        if: | 
          github.event.pull_request.base.ref == 'acceptance' &&
          ! startsWith(github.event.pull_request.head.ref, 'hotfix/') && 
          github.event.pull_request.head.ref != 'development' && 
          github.event.pull_request.head.ref != 'production'
        run: |
          echo "::error::Only following branches can be merged to acceptance: production, development, hotfix/*"
          exit 1
      - name: branch_chack_development
        if: | 
          github.event.pull_request.base.ref == 'development' &&
          ! startsWith(github.event.pull_request.head.ref, 'feature/') && 
          ! startsWith(github.event.pull_request.head.ref, 'mergefix/') && 
          github.event.pull_request.head.ref != 'acceptance' && 
          github.event.pull_request.head.ref != 'production'
        run: |
          echo "::error::Only following branches can be merged to acceptance: production, acceptance, feature/*, mergefix/*"
          exit 1
      - name: branch_check_production
        if: |
          github.event.pull_request.base.ref == 'production' &&
          github.event.pull_request.head.ref != 'acceptance'
        run: |
          echo "::error::Only following branches can be merged to production: acceptance"
          exit 1


