
name: validate-pr-acceptance

on:
  pull_request_target:
    branches: acceptance
    types: [ opened, edited, reopened, synchronized ]

jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: check-acceptance-pr
        if: | 
          github.event.pull_request.base.ref == 'acceptance' &&
          ! startsWith(github.event.pull_request.head.ref, 'hotfix/') && 
          ! startsWith(github.event.pull_request.head.ref, 'chore-acc/') && 
          github.event.pull_request.head.ref != 'development' && 
          github.event.pull_request.head.ref != 'production'
        run: |
          echo "::error::Only following branches can be merged to acceptance: production, development, hotfix/*, chore-acc/*"
          exit 1

