# This is a basic workflow to help you get started with Actions

name: validate-pr-acceptance

# Controls when the action will run. 
on:
  pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: branch_chack
        if: | 
          github.event.pull_request.base.ref == 'acceptance' &&
          ! startsWith(github.event.pull_request.head.ref, 'hotfix/') && 
          github.event.pull_request.head.ref != 'development' && 
          github.event.pull_request.head.ref != 'production'
        run: |
          echo "::error::You can only merge branches with hotfix prefix, development or production to acceptance"
          exit 1
