name: validate-pr-development

# Controls when the action will run. 
on:
  pull_request_target:
    branches: development
    types: [ opened, edited, reopened, synchronized ]
jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: check-dev-pr
        if: | 
          github.event.pull_request.base.ref == 'development' &&
          ! startsWith(github.event.pull_request.head.ref, 'feature/') && 
          ! startsWith(github.event.pull_request.head.ref, 'mergefix/') && 
          ! startsWith(github.event.pull_request.head.ref, 'chore-dev/') && 
          github.event.pull_request.head.ref != 'acceptance' && 
          github.event.pull_request.head.ref != 'production'
        run: |
          echo "::error::Only following branches can be merged to development: production, acceptance, feature/*, mergefix/*, chore-dev/*"
          exit 1
