
name: validate-pr-prod

on:
  pull_request_target:
    branches: production
    types: [ opened, edited, reopened, synchronized ]
jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: check-prod-pr
        if: |
            github.event.pull_request.base.ref == 'production' &&
            github.event.pull_request.head.ref != 'acceptance' &&
            ! startsWith(github.event.pull_request.head.ref, 'chore-prod/')
        run: |
            echo "::error::Only following branches can be merged to production: acceptance, chore-prod/*"
            exit 1

