
name: validate-pr-acceptance

# Controls when the action will run. 
on:
  pull_request_target:
    branches: production
    types: [ opened, edited, reopened, synchronized ]
jobs:
  # This workflow contains a single job called "build"
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: check-prod-pr
        if: |
            github.event.pull_request.base.ref == 'production' &&
            github.event.pull_request.head.ref != 'acceptance'
        run: |
            echo "::error::Only following branches can be merged to production: acceptance"
            exit 1

